meta_product_name: "Baybe"
meta_title: "Baybe - Baby's get more, you pay less."
meta_description: "We need to write description!"
meta_image: "baybelogo.png" # should exist in `app/assets/images/`
# facebook_account: "https://www.facebook.com/baybe.baybe.50951"
